config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  get "show_tweets" => "tweets#show_tweets"
    resources :tweets do
    resources :comments, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tweets
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{@comment.tweet.id}"
  end

  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  before_action :manji, except: :index

  def index
  end

  def new
  end

  def create
    post.create(post_params)
  end

  private
  def post_params
    params.permit(:name, :text)
  end

  def manji
    redirect_to action: :index unless user_signed_in?
  end

  def users_tweets
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: @user.id).all.order("created_at DESC").page(params[:page]).per(20)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @user = current_user
    @tweets = Tweet.page(params[:page]).per(20)
  end

  def new
  end

  def create
    Tweet.create(text: tweet_params[:text], user_id: current_user.id)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params) if tweet.user_id == current_user.id.order("created_at DESC").page(params[:page]).per(20)
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
  end

  def show_tweets
    @user = current_user
    @tweets = Tweet.where(user_id: @user.id).all.order("created_at DESC").page(params[:page]).per(20)
  end

  private
  def tweet_params
    params.permit(:text)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def users_tweets
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: @user.id).all.order("created_at DESC").page(params[:page]).per(20)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ikituke4
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
%link{:href => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", :rel => "stylesheet", :type => "text/css"}/
%link{:href => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css", :rel => "stylesheet", :type => "text/css"}/
%script{:src => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", :type => "text/javascript"}

app/views/tweets/create.html.haml
.contents.row
  .success
    %h2
      投稿が完了しました。
    = link_to '投稿一覧へ戻る', tweets_path, {class: 'btn btn-primary withripple' }

app/views/tweets/destroy.html.haml
.contents.row
  .success
    %h2
      削除が完了しました。
    = link_to '投稿一覧へ戻る', tweets_path, {class: 'btn btn-primary withripple' }

app/views/tweets/edit.html.haml
.contents.row
  = form_tag("/tweets/#{@tweet.id}", method: :patch ) do
    %h2
      編集する
    %textarea{:cols => "30", :name => "text", :placeholder => "text", :rows => "10"}= @tweet.text
    %br/
    %input{:type => "submit", :value => "変更する"}/

app/views/tweets/index.html.haml
%h2 ツイート検索
= link_to 'ツイートを投稿する', new_tweet_path, {class: 'btn btn-primary withripple' }
= link_to '自分のツイート一覧へ', show_tweets_path, {class: 'btn btn-primary withripple' }
- @tweets.each do |tweet|
  .contents.row
    .name3
      投稿者:#{link_to tweet.user.name, new_tweet_path(tweet.user), method: :get}
    .name2
      投稿日時:#{tweet.created_at.strftime("%Y-%m-%d %H:%M:%S")}
    .name2= link_to '詳細', tweet_path(tweet), method: :get
    - if user_signed_in? && current_user.id == tweet.user
      .name2
        = link_to '編集', edit_tweet_path(tweet), method: :get
      .name2
        = link_to '削除', "/tweets/#{tweet.id}", method: :delete
    .name3= simple_format(tweet.text)
= paginate(@tweets)

app/views/tweets/new.html.haml
.contents.row
  = form_tag('/tweets', method: :post) do
    %h2
      投稿する
    %textarea{:cols => "30", :name => "text", :placeholder => "text", :rows => "10"}
    %br/
    %input{:type => "submit", :value => "投稿する"}/

app/views/tweets/show.html.haml
%h2 投稿
.contents.row
  .name3
    -# 投稿者:#{link_to @tweet.user, user_path(@tweet.user), method: :get}
  .name2
    投稿日時:#{@tweet.created_at.strftime("%Y-%m-%d %H:%M:%S")}
  - if user_signed_in? && current_user.id == @tweet.user
    .name2
      = link_to '編集', edit_tweet_path(@tweet), method: :get
    .name2
      = link_to '削除', "/tweets/#{@tweet.id}", method: :delete
  .name3= simple_format(@tweet.text)
.contents.row
  %h2 コメント一覧
  - if @comments
    - @comments.each do |comment|
      .name2
        投稿者:#{link_to comment.user.name, "/users/#{comment.user_id}"}  投稿日時:#{comment.created_at.strftime("%Y-%m-%d %H:%M:%S")}
      .name2= comment.text
  %br/
  - if current_user
    = form_tag("/tweets/#{@tweet.id}/comments", method: :post) do
      %textarea{:cols => "30", :name => "text", :placeholder => "コメントする", :rows => "2"}
      %br/
      %input{:type => "submit", :value => "コメントの投稿"}/

app/views/tweets/show_tweets.html.haml
%h2 自分のツイート一覧
= link_to 'ツイートを投稿する', new_tweet_path, {class: 'btn btn-primary withripple' }
- @tweets.each do |tweet|
  .contents.row
    .name3
      投稿者:#{link_to tweet.user.name, root_path(tweet.user), method: :get}
    .name2
      投稿日時:#{tweet.created_at.strftime("%Y-%m-%d %H:%M:%S")}
    .name2= link_to '詳細', tweet_path(tweet), method: :get
    - if user_signed_in? && current_user.id == tweet.user
      .name2
        = link_to '編集', edit_tweet_path(tweet), method: :get
      .name2
        = link_to '削除', "/tweets/#{tweet.id}", method: :delete
    .name3= simple_format(tweet.text)
= paginate(@tweets)

app/views/tweets/update.html.haml
.contents.row
  .success
    %h2
      更新が完了しました。
    = link_to '投稿一覧へ戻る', tweets_path, {class: 'btn btn-primary withripple' }

app/views/tweets/users_tweets.html.haml
%h2
  = @user.username
  のツイート一覧
= link_to 'ツイートを投稿する', new_tweet_path, {class: 'btn btn-primary withripple' }
- @tweets.each do |tweet|
  .contents.row
    .name3
      投稿者:#{link_to tweet.user.username, user_path(tweet.user), method: :get}
    .name2
      投稿日時:#{tweet.created_at.strftime("%Y-%m-%d %H:%M:%S")}
    .name2= link_to '詳細', tweet_path(tweet), method: :get
    - if user_signed_in? && current_user.id == tweet.user_id
      .name2
        = link_to '編集', edit_tweet_path(tweet), method: :get
      .name2
        = link_to '削除', "/tweets/#{tweet.id}", method: :delete
    .name3= simple_format(tweet.text)
= paginate(@tweets)

app/views/users/users_tweets.html.haml
%h2
  = @user.username
  のツイート一覧
= link_to 'ツイートを投稿する', new_tweet_path, {class: 'btn btn-primary withripple' }
- @tweets.each do |tweet|
  .contents.row
    .name3
      投稿者:#{link_to tweet.user.username, user_path(tweet.user), method: :get}
    .name2
      投稿日時:#{tweet.created_at.strftime("%Y-%m-%d %H:%M:%S")}
    .name2= link_to '詳細', tweet_path(tweet), method: :get
    - if user_signed_in? && current_user.id == tweet.user_id
      .name2
        = link_to '編集', edit_tweet_path(tweet), method: :get
      .name2
        = link_to '削除', "/tweets/#{tweet.id}", method: :delete
    .name3= simple_format(tweet.text)
= paginate(@tweets)